version: '3.8'

services:
  database:
    image: mysql:latest
    restart: unless-stopped
    environment: 
      ACCEPT_EULA: 'Y'
      MYSQL_ROOT_PASSWORD: '2006'
      MYSQL_PASS: '2006'
      MYSQL_DATABASE: "vendor"
    volumes:
      - "database:/var/lib/mysql:rw"
    ports:
      - "1000:3306"
  frontend:
    build: ./Frontend/vendor-frontend/
    ports:
      - "8080:3000"
  backend:
    build: ./vendor/
    depends_on:
      - database
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://database:3306/vendor?autoReconnect=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "2006",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    ports:
      - "9090:8000"
    volumes: 
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    restart: unless-stopped


volumes:
  database: